### ISSUE TITLE
How can i do that for competitive?

### ISSUE THREAD

**Issue by ToPGameSyoutube** [NairasLT/cs-go-autoqueue#1]
if (colors[1].Contains("255 24 24 24"))
                    {

                        if (colors[9].Contains("255 255 255 255") || colors[9].Contains("255 90 90 90")) //CHECK FOR COMPETITIVE
                        {
                            if (colors[3].Contains("255 14 73 16"))
                            {
                                getfrgwnd[3] = GetForegroundWindow();
                                SetTopMost(windowHandle);
                                Thread.Sleep(100);
                                ClickOnPoint(windowHandle, new Point(312, 290));
                                SetNotTopMost(windowHandle);
                                SetForegroundWindow(getfrgwnd[3]);
                            }
                        }

                        else
                        {
                            getfrgwnd[7] = GetForegroundWindow();
                            SetTopMost(windowHandle);
                            Thread.Sleep(20);
                            ClickOnPoint(windowHandle, new Point(55, 58));
                            SetNotTopMost(windowHandle);
                            SetForegroundWindow(getfrgwnd[7]);
                        }

                    }

//I tried to change the numbers of the buttons but it's not working...
//Can you help me?
//I wanna use that for my vertigo boost panel.

**Comment by NairasLT** [comment]
Redownload cs-go-autoqueue, i added support for competitive and optional feature to show each cs:go window accepted matches.
